CREATE DATABASE IF NOT EXISTS BD_VISIO;
USE BD_VISIO;
CREATE TABLE ADMIN (
    CNPJ     VARCHAR(18)  PRIMARY KEY,
    EMAIL    VARCHAR(150) NOT NULL,
    TELEFONE VARCHAR(20)  NOT NULL,
    SENHA    VARCHAR(255) NOT NULL    
);

CREATE TABLE SENSOR (
    ID_SENSOR INT          AUTO_INCREMENT PRIMARY KEY,
    NOME      VARCHAR(100) NOT NULL,
    FOTO      VARCHAR(255) NOT NULL DEFAULT '',
    DESCRICAO VARCHAR(255) NOT NULL,
    CIRCUITO  VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE TABLE PERGUNTA (
    ID_PERGUNTA      INT          AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO        VARCHAR(255) NOT NULL,
    NIVEL_DIFICULDADE VARCHAR(20) NOT NULL
);

CREATE TABLE ALTERNATIVA (
    ID_ALTERNATIVA INT         AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO      VARCHAR(255) NOT NULL,
    IS_CORRETA     TINYINT(1)  NOT NULL DEFAULT 0,
    FK_ID_PERGUNTA INT         NOT NULL,
    FOREIGN KEY (FK_ID_PERGUNTA)
        REFERENCES PERGUNTA (ID_PERGUNTA)
        ON DELETE CASCADE
);

CREATE TABLE USUARIO (
    CPF              VARCHAR(14)  PRIMARY KEY,
    EMAIL            VARCHAR(150) NOT NULL UNIQUE,
    SENHA            VARCHAR(255) NOT NULL,
    CARTAO           VARCHAR(25)  NOT NULL DEFAULT '',
    DATA_NASCIMENTO  DATE         NOT NULL,
    TELEFONE         VARCHAR(20)  NOT NULL
);

CREATE TABLE RESPONDE (
    ID_RESPONDE      INT         AUTO_INCREMENT PRIMARY KEY,
    FK_CPF_USUARIO   VARCHAR(14) NOT NULL,
    FK_ID_ALTERNATIVA INT        NOT NULL,
    RESPONDIDO_EM    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FK_CPF_USUARIO)
        REFERENCES USUARIO (CPF)
        ON DELETE CASCADE,
    FOREIGN KEY (FK_ID_ALTERNATIVA)
        REFERENCES ALTERNATIVA (ID_ALTERNATIVA)
        ON DELETE CASCADE
);

-- ADMIN 1
-- Senha: Admin@123  →  hash bcrypt gerado via PHP password_hash()
-- Para gerar novo hash: php -r "echo password_hash('Admin@123', PASSWORD_BCRYPT);"
INSERT INTO ADMIN (CNPJ, EMAIL, TELEFONE, SENHA) VALUES
('12.345.678/0001-01', 'admin@visio.com', '11987654321', '$2y$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi');